"""Deterministic offline provider for tests, CI, and running the stack without API keys.

It produces a plausible, prompt-derived review and streams it word by word with a small delay,
so the live-streaming UI is observable. ``calls`` counts invocations — the cache tests assert on it.
"""

import re
import threading
import time
from collections.abc import Iterator

from app.llm.adapter import LLMEvent, LLMRequest, TextDelta, Usage


class FakeProvider:
    name = "fake"
    _lock = threading.Lock()
    calls = 0  # process-wide, across instances

    def __init__(self, model: str = "fake-reviewer-1", delay_ms: int = 15):
        self.model = model
        self.delay = delay_ms / 1000

    @classmethod
    def reset_calls(cls) -> None:
        with cls._lock:
            cls.calls = 0

    def _compose(self, request: LLMRequest) -> str:
        path = re.search(r"^File: (.+)$", request.user, re.MULTILINE)
        units = re.findall(r"^#### Changed unit: (.+)$", request.user, re.MULTILINE)
        similar = re.findall(r"^#### Similar code: (.+)$", request.user, re.MULTILINE)
        lines = [
            "### Summary",
            f"Reviewed `{path.group(1) if path else 'file'}` "
            f"({len(units)} changed unit{'s' if len(units) != 1 else ''}).",
            "",
            "### Findings",
        ]
        for unit in units[:5] or ["the diff"]:
            lines.append(
                f"- **[minor]** `{unit}` — consider adding a test that covers this change."
            )
        if similar:
            lines.append(
                f"- **[nit]** Compare with the existing pattern in `{similar[0]}` for consistency."
            )
        lines += ["", "### Verdict", "Looks reasonable (generated by the offline fake reviewer)."]
        return "\n".join(lines)

    def stream(self, request: LLMRequest) -> Iterator[LLMEvent]:
        with self._lock:
            type(self).calls += 1
        text = self._compose(request)
        for piece in re.findall(r"\S+\s*|\s+", text):
            if self.delay:
                time.sleep(self.delay)
            yield TextDelta(piece)
        yield Usage(
            input_tokens=len(request.system + request.user) // 4, output_tokens=len(text) // 4
        )
